### ISSUE TITLE
CONTRACT: Build a function to get all the borrow proposals

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#68] opened 2024-11-25 11:40 UTC
This function should retrieve all the borrow proposals from the contract storage so that they can be displayed on the frontend.

write the function and write the tests for it.

**Comment by emarc99** [comment] 2024-11-25 11:41
Can I attempt this issue?

**Comment by martinvibes** [comment] 2024-11-25 11:45
hey @Dprof-in-tech kindly assign

**Comment by vestor-dev** [comment] 2024-11-25 11:46
hey @Dprof-in-tech can i work on this issue

**Comment by ryzen-xp** [comment] 2024-11-25 11:48
Hello can I try this.  I have already created the borrow function for this project please assign me

**Comment by mimisavage** [comment] 2024-11-25 23:19
Can I take this from here?

**Comment by casweeney** [comment] 2024-11-26 01:08
## I can work on this:

### Tackling this issue:
- Looking at the current codebase, there is not storage variable of type vector that is holding the proposal. This implementation will be a bit tricky, I will create a loop that loops through the proposal count and in each loop iteration, I will use the iteration count to read from the `proposals` mapping which will be pushed into an array.
- Before pushing proposals into the array, I will filter the proposals using the `ProposalType`.
- Lastly, I will return the array that contains the Borrow proposal.
- I will write test for the function to be sure it works as intended

## ETA: 8 - 10 hours tops

**Comment by NueloSE** [comment] 2024-11-26 03:41
I’d like to resolve this.

i am a frontend developer with experience in writing and testing smart contract using cairo and solidity.

Kindly assign ETA <= 5hrs

**Comment by codebestia** [comment] 2024-11-26 04:22
Can i work on this?

**Comment by Birdmannn** [comment] 2024-11-26 05:08
Hey, my chief, can I handle this issue? I'm Torti Pascal, a Blockchain developer who demonstrates his expertise in Cairo Starknet ecosystem. I'll retrieve all the borrow proposals from the contract storage, and ideally it'll take me less than a day (if not hours).

**Comment by Yunusabdul38** [comment] 2024-11-26 05:43
hey @Dprof-in-tech can I work on this issue

**Comment by Supa-mega** [comment] 2024-11-26 07:34
May I pick this up? first time contributor

**Comment by anihdev** [comment] 2024-11-26 08:24
Im Anih Somadina, a Backend developer, experienced in writing Cairo and Solidity. As a fresh contributor Im familair with the codebase. ill study the Borrow proposal function and and create a suitable view function that can get the proposals and also write unit tests to ensure they respond as intended

**Comment by omsant02** [comment] 2024-11-26 08:41
i would like to solve this issue,

would create a function similar to get_lending_proposal_details() but with a condition filter for ProposalType::BORROWING, iterating through all proposals in storage and return array

**Comment by blessingbytes** [comment] 2024-11-26 09:06
Pls can I tackle this one?

**Comment by harshaktg** [comment] 2024-11-26 10:31
Hello maintainer @sasasamaes , I am new here. I am a developer with more than 8 years experience. Can you assign this to me? I will love to contribute to your project.

**Closed** 2024-11-27 05:56 UTC
Labels: good first issue, ODHack10, difficulty: easy
