### ISSUE TITLE
FE: Build out the referrals page

### ISSUE THREAD

**Issue by Dprof-in-tech** [Peerprotocol/peer-on-strk#51] opened 2024-11-21 13:43 UTC
https://www.figma.com/design/iW3cyAME5y74CegO0726ki/peer.protocol-quests?m=auto&t=SCxMYzYz92hgX4z3-1

here's the link to the figma and your job is to replicate exactly the referrals page.
The side bar is already built out and can be found in the /frontend/app/app folder. kindly import it in the page. Don't forget to make it mobile responsive too..

Criteria to be assigned:

follow the guidelines as given in the Od Hackers community group and dont forget to provide an ETA when applying

**Comment by Supa-mega** [comment] 2024-11-21 14:02
Can I take this from here?

**Comment by omsant02** [comment] 2024-11-21 14:04
May I be assigned to this?

**Comment by Supa-mega** [comment] 2024-11-21 14:04
can i be assigned this ?

**Comment by SYLVIANNORUKA** [comment] 2024-11-21 14:09
I'd love to work on this!I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, Cairo and Rust. I would love to contribute to this project.

**Comment by Benjtalkshow** [comment] 2024-11-21 14:11
Can I contribute to this one? 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

**Comment by Shalomnze** [comment] 2024-11-21 14:14
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would make use of layout since the side bar and navigation are consistent throughout the project so they will be component of the default layout would be consistent. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.

**Comment by 0xdevcollins** [comment] 2024-11-21 14:17
Can I take care of this issue?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 10 OnlyDust projects.

ETA: 24hrs

**Comment by Yunusabdul38** [comment] 2024-11-21 14:21
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by zintarh** [comment] 2024-11-21 14:26
Can I attempt this issue?
I would approch it by:
Import Sidebar: Import the sidebar from /frontend/app/app and integrate it into the page layout.
Replicate Layout: Use Flexbox or Grid to match the page structure from Figma (header, main body, and footer).
UI Components: Implement the referral table, buttons (Invite/View), and filters (search, date range) based on the design.
Mobile Responsiveness: Use media queries to ensure the page is fully responsive, adjusting the table, sidebar, and buttons for mobile.
Styling: Apply exact colors, typography, margins, and padding as in Figma for consistent design.
Dynamic Interactions: Implement any necessary table interactions (sorting, pagination) per the design.
ETA: 2 business day  (including integration, styling, responsiveness, and testing).

**Comment by Awointa** [comment] 2024-11-21 14:26
REACT developer at your service

**Comment by ShantelPeters** [comment] 2024-11-21 14:27
Could I take on this issue?

**Comment by Ayoazeez26** [comment] 2024-11-21 14:28
Could I try solving this?
I would implement the referrals page to pixel perfection using the figma file

ETA - 2 days

**Comment by Akshola00** [comment] 2024-11-21 14:34
Could I take on this issue?

**Comment by Stephy-Crown** [comment] 2024-11-21 14:34
Let me try this one!

**Comment by Aditya-040** [comment] 2024-11-21 14:35
May I handle this issue?

**Comment by mimisavage** [comment] 2024-11-21 14:41
Is it okay if I take this?

**Comment by Villarley** [comment] 2024-11-21 15:11
I’m Santiago Villarreal Arley, a proactive developer with experience in front-end and back-end Web3 development. As a member of Dojo Coding, I’ve worked on projects built on StarkNet and Stellar, focusing on creating scalable and user-friendly solutions. I’m also a Web3 hackathon Buildathon winner for my work on BuildMyEvent.

For this task, I’ll replicate the referrals page exactly as designed in the provided Figma link. I’ll import the sidebar component from /frontend/app/app and ensure the page is fully mobile responsive. I’ll follow all guidelines to make exactly what you are asking for.

ETA: 2-3 Days

Pls feel free to reach out

**Comment by Shalomnze** [comment] 2024-11-21 15:12
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would import it in the referral page. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.  ETA is 36hrs

**Comment by Shalomnze** [comment] 2024-11-21 15:19
Can I take this issue?

**Comment by Shalomnze** [comment] 2024-11-21 15:29
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would import it in the referral page. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.  ETA is 36hrs

**Comment by Shalomnze** [comment] 2024-11-21 15:29
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would import it in the referral page. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.  ETA is 36hrs

**Comment by Shalomnze** [comment] 2024-11-21 15:29
Let me handle this issue!

**Comment by Shalomnze** [comment] 2024-11-21 15:31
Let me handle this issue!

**Comment by Shalomnze** [comment] 2024-11-21 15:34
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would import it in the referral page. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.  ETA is 36hrs

**Comment by Shalomnze** [comment] 2024-11-21 15:44
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would import it in the referral page. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.  ETA is 36hrs

**Comment by Shalomnze** [comment] 2024-11-21 15:44
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would import it in the referral page. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.  ETA is 36hrs

**Comment by Shalomnze** [comment] 2024-11-21 15:44
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would import it in the referral page. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.  ETA is 36hrs

**Comment by Shalomnze** [comment] 2024-11-21 15:46
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would import it in the referral page. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.  ETA is 36hrs

**Comment by Shalomnze** [comment] 2024-11-21 15:49
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would import it in the referral page. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.  ETA is 36hrs

**Comment by Shalomnze** [comment] 2024-11-21 15:52
I would love to contribute to this project.

I would use tailwind CSS for my styling then I would import it in the referral page. I am expecting the referrals to come as an array of object so I would loop through the array to return the name icon and experience points for each position. I would then write a function that displays emoji symbols for first second and third instead of the position.  ETA is 36hrs

**Comment by melnikga** [comment] 2024-11-21 16:21
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga
ETA: 2 days

**Comment by ONEONUORA** [comment] 2024-11-21 16:40
Could I take on this issue?

**Comment by Shalomnze** [comment] 2024-11-21 17:06
I am Nze Shalom Ugochukwu, a full-stack developer with a strong foundation in modern web development frameworks and technologies. My expertise includes: Nuxt.js, Next.js and Tailwind CSS. I am Experienced in crafting responsive, visually appealing designs using Tailwind CSS, ensuring consistency and efficiency in the development process. 

I would love to contribute to this project. My approach to implementing the dashboard styling would be using Tailwind CSS for styling. I’d then import necessary dependencies and components, such as the side navigation, which is already available. By applying position: fixed, the side nav would remain fixed throughout scrolling for consistent usability. I’d retrieve the required styling for header text and paragraphs directly from the Figma design to maintain alignment with the project’s visual identity. In handling the referral data I am assuming the data would come as an array of objects, I’d loop through the array to dynamically render the name, icon, and experience points for each position.To enhance the user experience, I’d write a function to display emoji symbols for the top three positions instead of numeric ranks.
With a clear understanding of the requirements, I estimate an ETA of 36 hours to complete this task. I’m confident in delivering a polished, efficient, and user-friendly solution.

**Comment by LazarusAA** [comment] 2024-11-21 18:06
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️ with experience in both front-end and back-end development, and I would love to tackle this issue. With my proficiency in TypeScript, JavaScript and experience working on the front-end aspects of my last few hackathons, I'm confident that I can contribute to this project efficiently.

My workflow:

- Replicate the Referrals page exactly as per the Figma design
- Import the existing sidebar from ```/frontend/app/app``` into the page
- Ensure the page is fully mobile responsive

ETA: 48 hrs

**Comment by Amarjeet325** [comment] 2024-11-21 18:08
Mind if I take this issue?

**Comment by vestor-dev** [comment] 2024-11-21 18:39
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by JoelVR17** [comment] 2024-11-21 19:29
## I'm Joel Vargas, and I'm a Frontend Developer
## Dojo Coding 🔥

# Implement Referrals Page

## Description
Replicate the **Referrals Page** from the provided Figma design exactly. Ensure the implementation adheres to design standards and is fully responsive for both desktop and mobile views.

---

## Requirements

### 1. **Page Layout**
- Build the **Referrals Page** using the design from the provided Figma link.
- Import the pre-built sidebar from `/frontend/app/app` folder into the page.

### 2. **Mobile Responsiveness**
- Ensure the page layout is fully responsive, adapting seamlessly to various screen sizes.
- Maintain functionality and readability on mobile devices.

### 3. **Design Consistency**
- Match the Figma design pixel-perfectly, including:
  - Typography
  - Colors
  - Spacing
  - Buttons and interactions

### 4. **Functional Components**
- Replicate all UI components and elements, ensuring:
  - Buttons and links are interactive.
  - Any animations or hover states from the design are implemented.

---

## Tasks

1. Import the pre-built sidebar.
2. Set up the page structure and styles to match the Figma design.
3. Build and integrate all required components for the Referrals Page.
4. Test for responsiveness and ensure it looks and functions perfectly on mobile devices.
5. Review the design and functionality to confirm adherence to the Figma mockup.

---

## ETA
Provide an estimated time to complete the task when applying, based on the following:
- **Layout and structure**: ~2-3 hours
- **Component creation and styling**: ~3-5 hours
- **Responsiveness and testing**: ~2-3 hours
- **Final review**: ~1 hour

Total ETA: ~8-12 hours depending on complexity and attention to detail.

---

## Acceptance Criteria
- The Referrals Page matches the Figma design exactly.
- The page is fully responsive for both desktop and mobile views.
- The sidebar is correctly imported and functional.
- The implementation adheres to the **Od Hackers community group** guidelines.

---

### Additional Notes
Reach out to the project manager or refer to the Od Hackers guidelines for any clarification or design questions.

**Comment by akintola4** [comment] 2024-11-21 20:49
Can I attempt this issue? i would love to build it , this is my  twitter account for my works https://x.com/photofola

**Comment by akintola4** [comment] 2024-11-21 21:11
Can I attempt this issue? i would love to build it , this is my  twitter account for my works https://x.com/photofola and a link to my recent two works for designers i work with. (https://ooido-kc4l.vercel.app/) & (https://webfleets.vercel.app/)

**Comment by Kaminar-i** [comment] 2024-11-22 00:47
Mind if I take this issue?
i'm new and would love to work on this 
please assign me 

eta: 48hrs

**Comment by aspiringLilCoder** [comment] 2024-11-22 05:30
Is it okay if I tackle this?

**Comment by Dprof-in-tech** [comment] 2024-11-23 06:59
@Shalomnze , please you have one hour to make a draft PR or you will be unassigned.

**Comment by Ayoazeez26** [comment] 2024-11-23 07:53
@Dprof-in-tech can I pick this up if it becomes available?

**Comment by omsant02** [comment] 2024-11-23 14:14
can i solve this issue @Dprof-in-tech ?

**Comment by omsant02** [comment] 2024-11-25 20:15
Please assign this issue to me @Dprof-in-tech 
Eta : 6 hrs

**Closed** 2024-11-25 20:40 UTC
Labels: good first issue, ODHack10, difficulty: easy
